
spring:
  application:
    name: user-ms
  jpa:
  hibernate:
    ddl-auto: true
  h2:
  console:
    enabled: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /user-ms/api-docs
  swagger-ui:
    path: /user-ms/swagger.html